# Generated by Django 4.2.9 on 2024-03-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_photo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
