# Generated by Django 4.2.9 on 2024-03-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_alter_photo_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
